// File generated by FlutterFire CLI (placeholder).
// 실제로는 `flutterfire configure` 명령을 한 번 실행하면
// 이 파일이 본인 Firebase 프로젝트의 실제 값으로 자동 교체됩니다.
//
// 사용 방법:
//   import 'firebase_options.dart';
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure` to enable web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─────────── PLACEHOLDER VALUES ───────────
  // 아래 값들은 임시 자리표시자입니다.
  // `flutterfire configure` 를 실행하면 실제 Firebase 콘솔의 값으로 교체됩니다.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL6MXSUnmsseR9x3yWoOjFouCgTjoGov4',
    appId: '1:844476454513:android:ae4d169dffd99f51cd6dd0',
    messagingSenderId: '844476454513',
    projectId: 'capstone-e1eea',
    storageBucket: 'capstone-e1eea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBzvZUdPEaQAtX2QCDb84blzCJSx5UvuA',
    appId: '1:844476454513:ios:94838adca5a5334dcd6dd0',
    messagingSenderId: '844476454513',
    projectId: 'capstone-e1eea',
    storageBucket: 'capstone-e1eea.firebasestorage.app',
    iosBundleId: 'com.example.flutterproject',
  );
}
